// src/libs/themes.js
// Theme definitions using your CSS classes
export const themes = {
    default: {
        name: "Simple",
        bgClass: "theme-default",
        fontClass: "font-sans text-white",
        buttonClass: "btn-default",
        cardClass: "card-default",
        imageClass: "img-default",
        profileShape: "circle",
        socialShape: "circle",
        linkShape: "rounded",
        hasPageAnimation: false,
    },
    aurora: {
        name: "Aurora Flow",
        bgClass: "theme-aurora",
        fontClass: "font-mono text-white",
        buttonClass: "btn-aurora",
        cardClass: "card-aurora",
        imageClass: "img-aurora",
        profileShape: "circle",
        socialShape: "circle",
        linkShape: "rounded",
        hasPageAnimation: true,
    },
    neon: {
        name: "Cyber Neon",
        bgClass: "theme-neon",
        fontClass: "font-mono text-white",
        buttonClass: "btn-neon",
        cardClass: "card-neon",
        imageClass: "img-neon",
        profileShape: "circle",
        socialShape: "circle",
        linkShape: "rounded",
        hasPageAnimation: true,
        fontFamily: "'Orbitron', monospace",
    },
    light: {
        name: "Light",
        bgClass: "bg-gradient-to-br from-blue-50 to-indigo-100",
        fontClass: "font-sans text-gray-700",
        buttonClass: "btn-light",
        cardClass: "card-light",
        imageClass: "img-light",
        profileShape: "circle",
        socialShape: "circle",
        linkShape: "rounded",
        hasPageAnimation: false,
    },
    starfield: {
        name: "Starfield",
        bgClass: "theme-starfield",
        fontClass: "font-sans text-white",
        buttonClass: "btn-starfield",
        cardClass: "card-starfield",
        imageClass: "img-starfield",
        profileShape: "circle",
        socialShape: "circle",
        linkShape: "rounded",
        hasPageAnimation: true,
        fontFamily: "'Space Grotesk', sans-serif",
    },
    gamer: {
        name: "Gaming Elite",
        bgClass: "theme-gamer",
        fontClass: "font-bold text-white",
        buttonClass: "btn-gamer",
        cardClass: "card-gamer",
        imageClass: "img-gamer",
        profileShape: "hexagon",
        socialShape: "square",
        linkShape: "gaming",
        hasPageAnimation: true,
        fontFamily: "'Rajdhani', sans-serif",
    },
    coder: {
        name: "Code Matrix",
        bgClass: "theme-coder",
        fontClass: "font-mono text-green-400",
        buttonClass: "btn-coder",
        cardClass: "card-coder",
        imageClass: "img-coder",
        profileShape: "square",
        socialShape: "square",
        linkShape: "code",
        hasPageAnimation: true,
        fontFamily: "'Fira Code', monospace",
    },
    hacker: {
        name: "Dark Hacker",
        bgClass: "theme-hacker",
        fontClass: "font-mono text-green-300",
        buttonClass: "btn-hacker",
        cardClass: "card-hacker",
        imageClass: "img-hacker",
        profileShape: "square",
        socialShape: "diamond",
        linkShape: "hack",
        hasPageAnimation: true,
        fontFamily: "'Source Code Pro', monospace",
    },
    elegant: {
        name: "Elegant Luxury",
        bgClass: "theme-elegant",
        fontClass: "font-serif text-white",
        buttonClass: "btn-elegant",
        cardClass: "card-elegant",
        imageClass: "img-elegant",
        profileShape: "circle",
        socialShape: "circle",
        linkShape: "elegant",
        hasPageAnimation: true,
        fontFamily: "'Playfair Display', serif",
    },
    funky: {
        name: "Funky Groove",
        bgClass: "theme-funky",
        fontClass: "font-bold text-white drop-shadow-lg",
        buttonClass: "btn-funky",
        cardClass: "card-funky",
        imageClass: "img-funky",
        profileShape: "star",
        socialShape: "blob",
        linkShape: "wavy",
        hasPageAnimation: true,
        fontFamily: "'Fredoka One', cursive",
    },
    feminine: {
        name: "Feminine Bloom",
        bgClass: "theme-feminine",
        fontClass: "font-light text-white",
        buttonClass: "btn-feminine",
        cardClass: "card-feminine",
        imageClass: "img-feminine",
        profileShape: "flower",
        socialShape: "heart",
        linkShape: "soft",
        hasPageAnimation: true,
        fontFamily: "'Dancing Script', cursive",
    },
    retro: {
        name: "Retro Wave",
        bgClass: "theme-retro",
        fontClass: "font-mono text-white",
        buttonClass: "btn-retro",
        cardClass: "card-retro",
        imageClass: "img-retro",
        profileShape: "circle",
        socialShape: "square",
        linkShape: "retro",
        hasPageAnimation: true,
        fontFamily: "'Righteous', cursive",
    },
    nature: {
        name: "Nature Zen",
        bgClass: "theme-nature",
        fontClass: "font-sans text-white",
        buttonClass: "btn-nature",
        cardClass: "card-nature",
        imageClass: "img-nature",
        profileShape: "leaf",
        socialShape: "circle",
        linkShape: "organic",
        hasPageAnimation: true,
        fontFamily: "'Nunito', sans-serif",
    },
    corporate: {
        name: "Corporate Pro",
        bgClass: "theme-corporate",
        fontClass: "font-sans text-white",
        buttonClass: "btn-corporate",
        cardClass: "card-corporate",
        imageClass: "img-corporate",
        profileShape: "square",
        socialShape: "square",
        linkShape: "business",
        hasPageAnimation: false,
        fontFamily: "'Inter', sans-serif",
    },
    cosmic: {
        name: "Cosmic Dreams",
        bgClass: "theme-cosmic",
        fontClass: "font-sans text-white",
        buttonClass: "btn-cosmic",
        cardClass: "card-cosmic",
        imageClass: "img-cosmic",
        profileShape: "circle",
        socialShape: "circle",
        linkShape: "cosmic",
        hasPageAnimation: true,
        fontFamily: "'Comfortaa', cursive",
    },
    nepal: {
        name: "Nepal Pride",
        bgClass: "theme-nepal",
        fontClass: "font-bold text-white",
        buttonClass: "btn-nepal",
        cardClass: "card-nepal",
        imageClass: "img-nepal",
        profileShape: "shield",
        socialShape: "diamond",
        linkShape: "nepal",
        hasPageAnimation: true,
        fontFamily: "'Mukti', sans-serif",
    },
    minecraft: {
        name: "Minecraft World",
        bgClass: "theme-minecraft",
        fontClass: "font-mono text-white",
        buttonClass: "btn-minecraft",
        cardClass: "card-minecraft",
        imageClass: "img-minecraft",
        profileShape: "square",
        socialShape: "square",
        linkShape: "pixelated",
        hasPageAnimation: true,
        fontFamily: "'Press Start 2P', monospace",
    },
    adventure: {
        name: "Adventure Explorer",
        bgClass: "theme-adventure",
        fontClass: "font-sans text-white",
        buttonClass: "btn-adventure",
        cardClass: "card-adventure",
        imageClass: "img-adventure",
        profileShape: "hexagon",
        socialShape: "diamond",
        linkShape: "compass",
        hasPageAnimation: true,
        fontFamily: "'Merriweather', serif",
    },
    anime: {
        name: "Anime Aesthetic",
        bgClass: "theme-anime",
        fontClass: "font-sans text-white",
        buttonClass: "btn-anime",
        cardClass: "card-anime",
        imageClass: "img-anime",
        profileShape: "circle",
        socialShape: "circle",
        linkShape: "anime",
        hasPageAnimation: true,
        fontFamily: "'Noto Sans JP', sans-serif",
    },
    cartoon: {
        name: "Cartoon Fun",
        bgClass: "theme-cartoon",
        fontClass: "font-bold text-white",
        buttonClass: "btn-cartoon",
        cardClass: "card-cartoon",
        imageClass: "img-cartoon",
        profileShape: "star",
        socialShape: "circle",
        linkShape: "bubbly",
        hasPageAnimation: true,
        fontFamily: "'Fredoka One', cursive",
    },
    galaxy: {
        name: "Galaxy Explorer",
        bgClass: "theme-galaxy",
        fontClass: "font-sans text-white",
        buttonClass: "btn-galaxy",
        cardClass: "card-galaxy",
        imageClass: "img-galaxy",
        profileShape: "circle",
        socialShape: "circle",
        linkShape: "cosmic",
        hasPageAnimation: true,
        fontFamily: "'Orbitron', monospace",
    },
    ocean: {
        name: "Ocean Depths",
        bgClass: "theme-ocean",
        fontClass: "font-sans text-white",
        buttonClass: "btn-ocean",
        cardClass: "card-ocean",
        imageClass: "img-ocean",
        profileShape: "circle",
        socialShape: "circle",
        linkShape: "wave",
        hasPageAnimation: true,
        fontFamily: "'Lato', sans-serif",
    },
    forest: {
        name: "Mystic Forest",
        bgClass: "theme-forest",
        fontClass: "font-serif text-white",
        buttonClass: "btn-forest",
        cardClass: "card-forest",
        imageClass: "img-forest",
        profileShape: "leaf",
        socialShape: "circle",
        linkShape: "organic",
        hasPageAnimation: true,
        fontFamily: "'Merriweather', serif",
    },
    egyptian: {
        name: "Ancient Egypt",
        bgClass: "theme-egyptian",
        fontClass: "font-serif text-white",
        buttonClass: "btn-egyptian",
        cardClass: "card-egyptian",
        imageClass: "img-egyptian",
        profileShape: "square",
        socialShape: "diamond",
        linkShape: "hieroglyph",
        hasPageAnimation: true,
        fontFamily: "'Cinzel', serif",
    },
    sakura: {
        name: "Sakura Blossom",
        bgClass: "theme-sakura",
        fontClass: "font-light text-white",
        buttonClass: "btn-sakura",
        cardClass: "card-sakura",
        imageClass: "img-sakura",
        profileShape: "flower",
        socialShape: "circle",
        linkShape: "petal",
        hasPageAnimation: true,
        fontFamily: "'Noto Sans JP', sans-serif",
    },
    viking: {
        name: "Viking Warrior",
        bgClass: "theme-viking",
        fontClass: "font-bold text-white",
        buttonClass: "btn-viking",
        cardClass: "card-viking",
        imageClass: "img-viking",
        profileShape: "shield",
        socialShape: "diamond",
        linkShape: "rune",
        hasPageAnimation: true,
        fontFamily: "'Norse', serif",
    },
    cyberpunk: {
        name: "Cyberpunk 2077",
        bgClass: "theme-cyberpunk",
        fontClass: "font-mono text-white",
        buttonClass: "btn-cyberpunk",
        cardClass: "card-cyberpunk",
        imageClass: "img-cyberpunk",
        profileShape: "hexagon",
        socialShape: "square",
        linkShape: "cyber",
        hasPageAnimation: true,
        fontFamily: "'Rajdhani', sans-serif",
    },
    medieval: {
        name: "Medieval Kingdom",
        bgClass: "theme-medieval",
        fontClass: "font-serif text-white",
        buttonClass: "btn-medieval",
        cardClass: "card-medieval",
        imageClass: "img-medieval",
        profileShape: "shield",
        socialShape: "diamond",
        linkShape: "scroll",
        hasPageAnimation: true,
        fontFamily: "'Uncial Antiqua', serif",
    },
    tropical: {
        name: "Tropical Paradise",
        bgClass: "theme-tropical",
        fontClass: "font-light text-white",
        buttonClass: "btn-tropical",
        cardClass: "card-tropical",
        imageClass: "img-tropical",
        profileShape: "circle",
        socialShape: "circle",
        linkShape: "wave",
        hasPageAnimation: true,
        fontFamily: "'Dancing Script', cursive",
    },
    artdeco: {
        name: "Art Deco Vintage",
        bgClass: "theme-artdeco",
        fontClass: "font-serif text-white",
        buttonClass: "btn-artdeco",
        cardClass: "card-artdeco",
        imageClass: "img-artdeco",
        profileShape: "diamond",
        socialShape: "square",
        linkShape: "deco",
        hasPageAnimation: true,
        fontFamily: "'Great Vibes', cursive",
    },
};

export const THEME_VALUES = Object.keys(themes);